"""Experimental Pi tool transport; campaign launch selection is unchanged.

Harbor 11a disables SSH streams with egress control. This prototype uses only
BaseEnvironment exec/upload/download, with one persistent task-side Pi process
so file mutation queues survive concurrent calls. A separate host SDK process
owns model I/O and transcripts. This module neither installs from the network
inside a task nor forwards provider credentials into one.
"""

import asyncio
import json
import shlex
import tempfile
import uuid
from pathlib import Path

from harbor.environments.base import BaseEnvironment
from harbor.models.task.config import NetworkMode


class OfflineTransportError(RuntimeError):
    """Remote write state is unknown; stop the host and close the Harbor task."""


class RemoteToolError(RuntimeError):
    """The helper returned a completed tool error."""


class RemoteCallCancelled(asyncio.CancelledError):
    """Cancellation with a confirmed terminal result from the helper."""


class OfflinePiTools:
    """One trial owns this helper; the Harbor trial still owns the container."""

    def __init__(self, environment: BaseEnvironment, *, cwd: str, node_dir: Path, pi_dir: Path):
        if environment.network_policy.network_mode != NetworkMode.NO_NETWORK:
            raise ValueError("Offline Pi requires the existing NO_NETWORK task")
        if environment.task_env_config.mcp_servers:
            raise ValueError("This prototype does not implement MCP transport")
        self.environment = environment
        self.cwd = cwd
        self.node_dir = node_dir
        self.pi_dir = pi_dir
        self.root = f"/tmp/harbor-pi-{uuid.uuid4().hex}"
        self._local = tempfile.TemporaryDirectory(prefix="harbor-pi-transport-")
        self.local = Path(self._local.name)
        self.closed = False
        self.settled = False
        self.calls: set[asyncio.Task] = set()
        self.failure: OfflineTransportError | None = None
        self._closing: asyncio.Task | None = None

    @staticmethod
    async def _finish_owned(operation):
        # Caller cancellation requests cannot cancel publication or settlement.
        # Keep the owning task alive and wait through every subsequent cancel.
        while not operation.done():
            try:
                await asyncio.shield(operation)
            except asyncio.CancelledError:
                pass
        if operation.cancelled():
            raise OfflineTransportError("Remote settlement is uncertain; stop the Harbor task")
        return operation.result()

    def _fail_closed(self):
        if self.failure is None:
            self.failure = OfflineTransportError(
                "Remote write or settlement is uncertain; stop the Harbor task"
            )
            for task in self.calls:
                if task is not asyncio.current_task():
                    task.cancel()
        return self.failure

    async def _exec(self, command: str):
        result = await self.environment.exec(command, timeout_sec=30)
        if result.return_code != 0:
            raise RuntimeError(f"Harbor Pi transport command failed ({result.return_code})")
        return result.stdout or ""

    async def _publish(self, name: str, value: dict):
        source = self.local / name
        source.write_text(json.dumps(value))
        await self.environment.upload_file(source, f"{self.root}/{name}.upload")
        await self._exec(f"mv {self.root}/{name}.upload {self.root}/{name}")
        source.unlink()

    async def _read(self, name: str):
        # Names are generated by this owner, never supplied by a tool or guest.
        exists = await self._exec(f"if test -f {self.root}/{name}; then echo ready; fi")
        if exists.strip() != "ready":
            return None
        target = self.local / name
        await self.environment.download_file(f"{self.root}/{name}", target)
        value = json.loads(target.read_text())
        target.unlink()
        return value

    async def _wait(self, name: str, timeout: float = 30):
        async with asyncio.timeout(timeout):
            while (value := await self._read(name)) is None:
                await asyncio.sleep(0.05)
            return value

    async def start(self):
        # mkdir is exclusive. No shared helper, attachment, guessed PID or retry.
        await self._exec(f"umask 077; mkdir {self.root}")
        await self.environment.upload_dir(self.node_dir, f"{self.root}/node")
        await self.environment.upload_dir(self.pi_dir, f"{self.root}/pi")
        await self.environment.upload_file(
            Path(__file__).with_name("anonbench1_offline_task_helper.mjs"), f"{self.root}/helper.mjs"
        )
        entry = f"{self.root}/pi/node_modules/@earendil-works/pi-coding-agent/dist/index.js"
        command = (
            f"env PI_CODING_AGENT_DIR={self.root}/config PI_OFFLINE=1 "
            f'PATH={self.root}/node/bin:{self.root}/pi/bin:"$PATH" '
            f"{self.root}/node/bin/node {self.root}/helper.mjs "
            f"{self.root} {shlex.quote(self.cwd)} {entry} "
            f">{self.root}/helper.log 2>&1 </dev/null &"
        )
        await self._exec(command)
        ready = await self._wait("ready")
        if ready["node"] != "v26.11.1" or ready["pi"] != "1.1.0":
            raise RuntimeError("Offline Pi runtime pin mismatch")
        return ready

    async def call(self, tool: str, call_id: str, args: dict, on_update=None, context=None):
        if self.failure is not None:
            raise self.failure
        if self.closed:
            raise OfflineTransportError("Offline Pi helper is closed")
        task = asyncio.current_task()
        self.calls.add(task)
        request_id = uuid.uuid4().hex
        try:
            # Shield publication: cancellation must not overtake an uncertain upload.
            publish = asyncio.create_task(
                self._publish(
                    f"{request_id}.request",
                    {"tool": tool, "callId": call_id, "args": args, "context": context},
                )
            )
            try:
                await asyncio.shield(publish)
                index = 0
                while True:
                    while (update := await self._read(f"{request_id}.update.{index}")) is not None:
                        if on_update:
                            await on_update(update)
                        index += 1
                    result = await self._read(f"{request_id}.result")
                    if result is not None and index == result["updates"]:
                        if not result["ok"]:
                            raise RemoteToolError(result["error"])
                        return result["result"]
                    await asyncio.sleep(0.05)
            except asyncio.CancelledError:
                settlement = asyncio.create_task(self._cancel_and_settle(publish, request_id))
                await self._finish_owned(settlement)
                raise RemoteCallCancelled() from None
        except RemoteToolError:
            raise
        except Exception as error:
            # A failed upload/rename/read may follow remote acceptance. It must
            # never become an ordinary tool error or permit another request.
            raise self._fail_closed() from error
        finally:
            self.calls.discard(task)

    async def _cancel_and_settle(self, publish, request_id):
        await publish
        await self._publish(f"{request_id}.cancel", {})
        result = await self._wait(f"{request_id}.result")
        if not isinstance(result, dict) or not isinstance(result.get("ok"), bool):
            raise OfflineTransportError("Remote settlement result is invalid")

    async def close(self):
        if self._closing is None:
            self.closed = True
            self._closing = asyncio.create_task(self._close())
        await self._finish_owned(self._closing)

    async def _close(self):
        for task in self.calls:
            task.cancel()
        await asyncio.gather(*self.calls, return_exceptions=True)
        await self._publish("stop", {})
        closed = await self._wait("closed")
        if closed.get("settled") is not True:
            raise RuntimeError("Offline Pi helper did not settle")
        self.settled = True
        # The enclosing trial's environment.stop owns all task process cleanup.
        self._local.cleanup()

    async def run_host(self, command: list[str], *, env: dict[str, str], cwd: Path):
        """Run a host SDK consumer using the paired JS client's control IPC."""
        process = await asyncio.create_subprocess_exec(
            *command,
            cwd=cwd,
            env=env,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            limit=16 * 1024 * 1024,
        )
        calls = {}
        seen = set()
        lock = asyncio.Lock()
        fatal = asyncio.get_running_loop().create_future()

        async def send(message):
            async with lock:
                process.stdin.write((json.dumps(message) + "\n").encode())
                await process.stdin.drain()

        async def invoke(message):
            identifier = message["id"]

            async def update(result):
                await send({"type": "update", "id": identifier, "result": result})

            try:
                result = await self.call(
                    message["tool"],
                    message["callId"],
                    message["args"],
                    update,
                    message.get("context"),
                )
                response = {"id": identifier, "ok": True, "result": result}
            except RemoteCallCancelled:
                response = {"id": identifier, "ok": False, "error": "aborted; remote call settled"}
            except RemoteToolError as error:
                response = {"id": identifier, "ok": False, "error": str(error)}
            except (OfflineTransportError, OSError, ValueError, KeyError, TypeError) as error:
                if not fatal.done():
                    fatal.set_result(error)
                return
            await send(response)

        stderr = asyncio.create_task(process.stderr.read())
        try:
            while True:
                read = asyncio.create_task(process.stdout.readline())
                try:
                    await asyncio.wait((read, fatal), return_when=asyncio.FIRST_COMPLETED)
                    if fatal.done():
                        raise fatal.result()
                    line = read.result()
                finally:
                    if not read.done():
                        read.cancel()
                    await asyncio.gather(read, return_exceptions=True)
                if not line:
                    break
                message = json.loads(line)
                identifier = message["id"]
                if message["type"] == "call" and identifier not in seen:
                    seen.add(identifier)
                    calls[identifier] = asyncio.create_task(invoke(message))
                elif message["type"] == "cancel" and identifier in calls:
                    calls[identifier].cancel()
                else:
                    raise RuntimeError("Invalid host tool protocol")
            await process.wait()
            if process.returncode:
                raise RuntimeError((await stderr).decode())
        finally:

            async def cleanup():
                # EOF rejects the SDK's pending IPC promises without claiming
                # remote settlement. Its SIGTERM handler can then finish abort.
                process.stdin.close()
                for task in calls.values():
                    if not task.done():
                        task.cancel()
                await asyncio.gather(*calls.values(), return_exceptions=True)
                if process.returncode is None:
                    process.terminate()
                    try:
                        async with asyncio.timeout(5):
                            await process.wait()
                    except TimeoutError:
                        # Only the child created above belongs to this owner.
                        process.kill()
                        await process.wait()
                await stderr

            await self._finish_owned(asyncio.create_task(cleanup()))
        if fatal.done():
            raise fatal.result()
